### ISSUE TITLE
Hyperparameters for the baseline?

### ISSUE THREAD

**Issue by jshin49** [IBM/dstc7-noesis#13]
Dear organizers,

Thank you for sharing the baseline so promptly.

I would like to replicate it in a PyTorch version. 

Do you have any hyperparameters to produce the results?

**Comment by chulakar** [comment]
Hi @jshin49, 
The hyper-parameters used in the model are [here](https://github.com/IBM/dstc7-noesis/blob/master/noesis-tf/hparams.py).
